version: "3"
services:
  ipfs:
    image: ipfs/go-ipfs
    dns:
      - 1.1.1.1
      - 8.8.8.8
    expose:
      - 5001
    ports:
      - 10.0.0.3:8080:8080
      - 0.0.0.0:4001:4001/tcp
      - 0.0.0.0:4001:4001/udp
    volumes:
      - /mnt/ipfs:/data/ipfs

  helper:
    build: helper
    depends_on:
      - ipfs
