version: "3"
services:
  ipfs:
    restart: always
    container_name: ipfs
    image: ipfs/go-ipfs
    network_mode: host
    volumes:
      - /mnt/ipfs:/data/ipfs

  helper:
    restart: always
    container_name: ipfs-helper
    build: helper
    network_mode: host
    depends_on:
      - ipfs
